apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo-app.fullname" . }}
  labels:
    {{- include "helm-demo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "helm-demo-app.selectorLabels" . | nindent 4 }}
