name: Docker Image CI

on:
  push
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: 
        docker login --username al3castro --password ${{ secrets.GH_PAT }} ghcr.io
    - uses: actions/checkout@v3
    - name: Login
      run: 
        docker build . -t ghcr.io/al3castro/ci-cd-demo-app:latest
    - uses: actions/checkout@v3
    - name: Login
      run: 
        docker push ghcr.io/al3castro/ci-cd-demo-app:latest
